// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXJ12mowajpvAi63LWaQZJj3HQLJiuIE8',
    appId: '1:631163278619:web:e0f2d58a07570dc0f5efbe',
    messagingSenderId: '631163278619',
    projectId: 'notes-f8786',
    authDomain: 'notes-f8786.firebaseapp.com',
    storageBucket: 'notes-f8786.appspot.com',
    measurementId: 'G-YENNR2FGQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDKARDWIeXSUslIvkSAT_Zsgs11jTqiew',
    appId: '1:631163278619:android:1129df9101a4718df5efbe',
    messagingSenderId: '631163278619',
    projectId: 'notes-f8786',
    storageBucket: 'notes-f8786.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW0PeHbpmZfPnpUV_BlTDM4S7cvpGKdJc',
    appId: '1:631163278619:ios:ccf0dbc221c1d586f5efbe',
    messagingSenderId: '631163278619',
    projectId: 'notes-f8786',
    storageBucket: 'notes-f8786.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW0PeHbpmZfPnpUV_BlTDM4S7cvpGKdJc',
    appId: '1:631163278619:ios:853112a1cae8eab2f5efbe',
    messagingSenderId: '631163278619',
    projectId: 'notes-f8786',
    storageBucket: 'notes-f8786.appspot.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
